export default [
  {
    name: 'Afghanistan',
    alpha2: 'AF',
    alpha2: 'AFG',
    alpha2: '004',
  },
  {
    name: 'Albania',
    alpha2: 'AL',
    alpha2: 'ALB',
    numeric: '008',
  },
  {
    name: 'Algeria',
    alpha2: 'DZ',
    alpha2: 'DZA',
    numeric: '012',
  },
  {
    name: 'American   Samoa',
    alpha2: 'AS',
    alpha2: 'ASM',
    numeric: '016',
  },
  {
    name: 'Andorra',
    alpha2: 'AD',
    alpha2: 'AND',
    numeric: '020',
  },
  {
    name: 'Angola',
    alpha2: 'AO',
    alpha2: 'AGO',
    numeric: '024',
  },
  {
    name: 'Anguilla',
    alpha2: 'AI',
    alpha2: 'AIA',
    numeric: '660',
  },
  {
    name: 'Antarctica',
    alpha2: 'AQ',
    alpha2: 'ATA',
    numeric: '010',
  },
  {
    name: 'Antigua and Barbuda',
    alpha2: 'AG',
    alpha2: 'ATG',
    numeric: '028',
  },
  {
    name: 'Argentina',
    alpha2: 'AR',
    alpha2: 'ARG',
    numeric: '032',
  },
  {
    name: 'Armenia',
    alpha2: 'AM',
    alpha2: 'ARM',
    numeric: '051',
  },
  {
    name: 'Aruba',
    alpha2: 'AW',
    alpha2: 'ABW',
    numeric: '533',
  },
  {
    name: 'Australia',
    alpha2: 'AU',
    alpha2: 'AUS',
    numeric: '036',
  },
  {
    name: 'Austria',
    alpha2: 'AT',
    alpha2: 'AUT',
    numeric: '040',
  },
  {
    name: 'Azerbaijan',
    alpha2: 'AZ',
    alpha2: 'AZE',
    numeric: '031',
  },
  {
    name: 'Bahamas (the)',
    alpha2: 'BS',
    alpha2: 'BHS',
    numeric: '044',
  },
  {
    name: 'Bahrain',
    alpha2: 'BH',
    alpha2: 'BHR',
    numeric: '048',
  },
  {
    name: 'Bangladesh',
    alpha2: 'BD',
    alpha2: 'BGD',
    numeric: '050',
  },
  {
    name: 'Barbados',
    alpha2: 'BB',
    alpha2: 'BRB',
    numeric: '052',
  },
  {
    name: 'Belarus',
    alpha2: 'BY',
    alpha2: 'BLR',
    numeric: '112',
  },
  {
    name: 'Belgium',
    alpha2: 'BE',
    alpha2: 'BEL',
    numeric: '056',
  },
  {
    name: 'Belize',
    alpha2: 'BZ',
    alpha2: 'BLZ',
    numeric: '084',
  },
  {
    name: 'Benin',
    alpha2: 'BJ',
    alpha2: 'BEN',
    numeric: '204',
  },
  {
    name: 'Bermuda',
    alpha2: 'BM',
    alpha2: 'BMU',
    numeric: '060',
  },
  {
    name: 'Bhutan',
    alpha2: 'BT',
    alpha2: 'BTN',
    numeric: '064',
  },
  {
    name: 'Bolivia (Plurinational   State   of)',
    alpha2: 'BO',
    alpha2: 'BOL',
    numeric: '068',
  },
  {
    name: 'Bonaire, Sint   Eustatius   and   Saba',
    alpha2: 'BQ',
    alpha2: 'BES',
    numeric: '535',
  },
  {
    name: 'Bosnia   and   Herzegovina',
    alpha2: 'BA',
    alpha2: 'BIH',
    numeric: '070',
  },
  {
    name: 'Botswana',
    alpha2: 'BW',
    alpha2: 'BWA',
    numeric: '072',
  },
  {
    name: 'Bouvet   Island',
    alpha2: 'BV',
    alpha2: 'BVT',
    numeric: '074',
  },
  {
    name: 'Brazil',
    alpha2: 'BR',
    alpha2: 'BRA',
    numeric: '076',
  },
  {
    name: 'British Indian   Ocean   Territory   (the)',
    alpha2: 'IO',
    alpha2: 'IOT',
    numeric: '086',
  },
  {
    name: 'Brunei   Darussalam',
    alpha2: 'BN',
    alpha2: 'BRN',
    numeric: '096',
  },
  {
    name: 'Bulgaria',
    alpha2: 'BG',
    alpha2: 'BGR',
    numeric: '100',
  },
  {
    name: 'Burkina Faso',
    alpha2: 'BF',
    alpha2: 'BFA',
    numeric: '854',
  },
  {
    name: 'Burundi',
    alpha2: 'BI',
    alpha2: 'BDI',
    numeric: '108',
  },
  {
    name: 'Cabo   Verde',
    alpha2: 'CV',
    alpha2: 'CPV',
    numeric: '132',
  },
  {
    name: 'Cambodia',
    alpha2: 'KH',
    alpha2: 'KHM',
    numeric: '116',
  },
  {
    name: 'Cameroon',
    alpha2: 'CM',
    alpha2: 'CMR',
    numeric: '120',
  },
  {
    name: 'Canada',
    alpha2: 'CA',
    alpha2: 'CAN',
    numeric: '124',
  },
  {
    name: 'Cayman   Islands   (the)',
    alpha2: 'KY',
    alpha2: 'CYM',
    numeric: '136',
  },
  {
    name: 'Central African Republic   (the)',
    alpha2: 'CF',
    alpha2: 'CAF',
    numeric: '140',
  },
  {
    name: 'Chad',
    alpha2: 'TD',
    alpha2: 'TCD',
    numeric: '148',
  },
  {
    name: 'Chile',
    alpha2: 'CL',
    alpha2: 'CHL',
    numeric: '152',
  },
  {
    name: 'China',
    alpha2: 'CN',
    alpha2: 'CHN',
    numeric: '156',
  },
  {
    name: 'Christmas Island',
    alpha2: 'CX',
    alpha2: 'CXR',
    numeric: '162',
  },
  {
    name: 'Cocos (Keeling) Islands (the)',
    alpha2: 'CC',
    alpha2: 'CCK',
    numeric: '166',
  },
  {
    name: 'Colombia',
    alpha2: 'CO',
    alpha2: 'COL',
    numeric: '170',
  },
  {
    name: 'Comoros (the)',
    alpha2: 'KM',
    alpha2: 'COM',
    numeric: '174',
  },
  {
    name: 'Congo (the   Democratic  Republic   of the)',
    alpha2: 'CD',
    alpha2: 'COD',
    numeric: '180',
  },
  {
    name: 'Congo (the)',
    alpha2: 'CG',
    alpha2: 'COG',
    numeric: '178',
  },
  {
    name: 'Cook   Islands   (the)',
    alpha2: 'CK',
    alpha2: 'COK',
    numeric: '184',
  },
  {
    name: 'Costa Rica',
    alpha2: 'CR',
    alpha2: 'CRI',
    numeric: '188',
  },
  {
    name: 'Croatia',
    alpha2: 'HR',
    alpha2: 'HRV',
    numeric: '191',
  },
  {
    name: 'Cuba',
    alpha2: 'CU',
    alpha2: 'CUB',
    numeric: '192',
  },
  {
    name: 'Curaçao',
    alpha2: 'CW',
    alpha2: 'CUW',
    numeric: '531',
  },
  {
    name: 'Cyprus',
    alpha2: 'CY',
    alpha2: 'CYP',
    numeric: '196',
  },
  {
    name: 'Czechia',
    alpha2: 'CZ',
    alpha2: 'CZE',
    numeric: '203',
  },
  {
    name: "Côte   d'Ivoire",
    alpha2: 'CI',
    alpha2: 'CIV',
    numeric: '384',
  },
  {
    name: 'Denmark',
    alpha2: 'DK',
    alpha2: 'DNK',
    numeric: '208',
  },
  {
    name: 'Djibouti',
    alpha2: 'DJ',
    alpha2: 'DJI',
    numeric: '262',
  },
  {
    name: 'Dominica',
    alpha2: 'DM',
    alpha2: 'DMA',
    numeric: '212',
  },
  {
    name: 'Dominican Republic   (the)',
    alpha2: 'DO',
    alpha2: 'DOM',
    numeric: '214',
  },
  {
    name: 'Ecuador',
    alpha2: 'EC',
    alpha2: 'ECU',
    numeric: '218',
  },
  {
    name: 'Egypt',
    alpha2: 'EG',
    alpha2: 'EGY',
    numeric: '818',
  },
  {
    name: 'El   Salvador',
    alpha2: 'SV',
    alpha2: 'SLV',
    numeric: '222',
  },
  {
    name: 'Equatorial   Guinea',
    alpha2: 'GQ',
    alpha2: 'GNQ',
    numeric: '226',
  },
  {
    name: 'Eritrea',
    alpha2: 'ER',
    alpha2: 'ERI',
    numeric: '232',
  },
  {
    name: 'Estonia',
    alpha2: 'EE',
    alpha2: 'EST',
    numeric: '233',
  },
  {
    name: 'Eswatini',
    alpha2: 'SZ',
    alpha2: 'SWZ',
    numeric: '748',
  },
  {
    name: 'Ethiopia',
    alpha2: 'ET',
    alpha2: 'ETH',
    numeric: '231',
  },
  {
    name: 'Falkland   Islands   (the)   [Malvinas]',
    alpha2: 'FK',
    alpha2: 'FLK',
    numeric: '238',
  },
  {
    name: 'Faroe Islands (the)',
    alpha2: 'FO',
    alpha2: 'FRO',
    numeric: '234',
  },
  {
    name: 'Fiji',
    alpha2: 'FJ',
    alpha2: 'FJI',
    numeric: '242',
  },
  {
    name: 'Finland',
    alpha2: 'FI',
    alpha2: 'FIN',
    numeric: '246',
  },
  {
    name: 'France',
    alpha2: 'FR',
    alpha2: 'FRA',
    numeric: '250',
  },
  {
    name: 'French   Guiana',
    alpha2: 'GF',
    alpha2: 'GUF',
    numeric: '254',
  },
  {
    name: 'French   Polynesia',
    alpha2: 'PF',
    alpha2: 'PYF',
    numeric: '258',
  },
  {
    name: 'French   Southern  Territories  (the)',
    alpha2: 'TF',
    alpha2: 'ATF',
    numeric: '260',
  },
  {
    name: 'Gabon',
    alpha2: 'GA',
    alpha2: 'GAB',
    numeric: '266',
  },
  {
    name: 'Gambia   (the)',
    alpha2: 'GM',
    alpha2: 'GMB',
    numeric: '270',
  },
  {
    name: 'Georgia',
    alpha2: 'GE',
    alpha2: 'GEO',
    numeric: '268',
  },
  {
    name: 'Germany',
    alpha2: 'DE',
    alpha2: 'DEU',
    numeric: '276',
  },
  {
    name: 'Ghana',
    alpha2: 'GH',
    alpha2: 'GHA',
    numeric: '288',
  },
  {
    name: 'Gibraltar',
    alpha2: 'GI',
    alpha2: 'GIB',
    numeric: '292',
  },
  {
    name: 'Greece',
    alpha2: 'GR',
    alpha2: 'GRC',
    numeric: '300',
  },
  {
    name: 'Greenland',
    alpha2: 'GL',
    alpha2: 'GRL',
    numeric: '304',
  },
  {
    name: 'Grenada',
    alpha2: 'GD',
    alpha2: 'GRD',
    numeric: '308',
  },
  {
    name: 'Guadeloupe',
    alpha2: 'GP',
    alpha2: 'GLP',
    numeric: '312',
  },
  {
    name: 'Guam',
    alpha2: 'GU',
    alpha2: 'GUM',
    numeric: '316',
  },
  {
    name: 'Guatemala',
    alpha2: 'GT',
    alpha2: 'GTM',
    numeric: '320',
  },
  {
    name: 'Guernsey',
    alpha2: 'GG',
    alpha2: 'GGY',
    numeric: '831',
  },
  {
    name: 'Guinea',
    alpha2: 'GN',
    alpha2: 'GIN',
    numeric: '324',
  },
  {
    name: 'Guinea-Bissau',
    alpha2: 'GW',
    alpha2: 'GNB',
    numeric: '624',
  },
  {
    name: 'Guyana',
    alpha2: 'GY',
    alpha2: 'GUY',
    numeric: '328',
  },
  {
    name: 'Haiti',
    alpha2: 'HT',
    alpha2: 'HTI',
    numeric: '332',
  },
  {
    name: 'Heard Island   and   McDonald Islands',
    alpha2: 'HM',
    alpha2: 'HMD',
    numeric: '334',
  },
  {
    name: 'Holy   See   (the)',
    alpha2: 'VA',
    alpha2: 'VAT',
    numeric: '336',
  },
  {
    name: 'Honduras',
    alpha2: 'HN',
    alpha2: 'HND',
    numeric: '340',
  },
  {
    name: 'Hong   Kong',
    alpha2: 'HK',
    alpha2: 'HKG',
    numeric: '344',
  },
  {
    name: 'Hungary',
    alpha2: 'HU',
    alpha2: 'HUN',
    numeric: '348',
  },
  {
    name: 'Iceland',
    alpha2: 'IS',
    alpha2: 'ISL',
    numeric: '352',
  },
  {
    name: 'India',
    alpha2: 'IN',
    alpha2: 'IND',
    numeric: '356',
  },
  {
    name: 'Indonesia',
    alpha2: 'ID',
    alpha2: 'IDN',
    numeric: '360',
  },
  {
    name: 'Iran   (Islamic  Republic   of)',
    alpha2: 'IR',
    alpha2: 'IRN',
    numeric: '364',
  },
  {
    name: 'Iraq',
    alpha2: 'IQ',
    alpha2: 'IRQ',
    numeric: '368',
  },
  {
    name: 'Ireland',
    alpha2: 'IE',
    alpha2: 'IRL',
    numeric: '372',
  },
  {
    name: 'Isle   of  Man',
    alpha2: 'IM',
    alpha2: 'IMN',
    numeric: '833',
  },
  {
    name: 'Israel',
    alpha2: 'IL',
    alpha2: 'ISR',
    numeric: '376',
  },
  {
    name: 'Italy',
    alpha2: 'IT',
    alpha2: 'ITA',
    numeric: '380',
  },
  {
    name: 'Jamaica',
    alpha2: 'JM',
    alpha2: 'JAM',
    numeric: '388',
  },
  {
    name: 'Japan',
    alpha2: 'JP',
    alpha2: 'JPN',
    numeric: '392',
  },
  {
    name: 'Jersey',
    alpha2: 'JE',
    alpha2: 'JEY',
    numeric: '832',
  },
  {
    name: 'Jordan',
    alpha2: 'JO',
    alpha2: 'JOR',
    numeric: '400',
  },
  {
    name: 'Kazakhstan',
    alpha2: 'KZ',
    alpha2: 'KAZ',
    numeric: '398',
  },
  {
    name: 'Kenya',
    alpha2: 'KE',
    alpha2: 'KEN',
    numeric: '404',
  },
  {
    name: 'Kiribati',
    alpha2: 'KI',
    alpha2: 'KIR',
    numeric: '296',
  },
  {
    name: "Korea (the   Democratic  People's   Republic of)",
    alpha2: 'KP',
    alpha2: 'PRK',
    numeric: '408',
  },
  {
    name: 'Korea (the   Republic  of)',
    alpha2: 'KR',
    alpha2: 'KOR',
    numeric: '410',
  },
  {
    name: 'Kuwait',
    alpha2: 'KW',
    alpha2: 'KWT',
    numeric: '414',
  },
  {
    name: 'Kyrgyzstan',
    alpha2: 'KG',
    alpha2: 'KGZ',
    numeric: '417',
  },
  {
    name: "Lao People's   Democratic  Republic   (the)",
    alpha2: 'LA',
    alpha2: 'LAO',
    numeric: '418',
  },
  {
    name: 'Latvia',
    alpha2: 'LV',
    alpha2: 'LVA',
    numeric: '428',
  },
  {
    name: 'Lebanon',
    alpha2: 'LB',
    alpha2: 'LBN',
    numeric: '422',
  },
  {
    name: 'Lesotho',
    alpha2: 'LS',
    alpha2: 'LSO',
    numeric: '426',
  },
  {
    name: 'Liberia',
    alpha2: 'LR',
    alpha2: 'LBR',
    numeric: '430',
  },
  {
    name: 'Libya',
    alpha2: 'LY',
    alpha2: 'LBY',
    numeric: '434',
  },
  {
    name: 'Liechtenstein',
    alpha2: 'LI',
    alpha2: 'LIE',
    numeric: '438',
  },
  {
    name: 'Lithuania',
    alpha2: 'LT',
    alpha2: 'LTU',
    numeric: '440',
  },
  {
    name: 'Luxembourg',
    alpha2: 'LU',
    alpha2: 'LUX',
    numeric: '442',
  },
  {
    name: 'Macao',
    alpha2: 'MO',
    alpha2: 'MAC',
    numeric: '446',
  },
  {
    name: 'Madagascar',
    alpha2: 'MG',
    alpha2: 'MDG',
    numeric: '450',
  },
  {
    name: 'Malawi',
    alpha2: 'MW',
    alpha2: 'MWI',
    numeric: '454',
  },
  {
    name: 'Malaysia',
    alpha2: 'MY',
    alpha2: 'MYS',
    numeric: '458',
  },
  {
    name: 'Maldives',
    alpha2: 'MV',
    alpha2: 'MDV',
    numeric: '462',
  },
  {
    name: 'Mali',
    alpha2: 'ML',
    alpha2: 'MLI',
    numeric: '466',
  },
  {
    name: 'Malta',
    alpha2: 'MT',
    alpha2: 'MLT',
    numeric: '470',
  },
  {
    name: 'Marshall   Islands   (the)',
    alpha2: 'MH',
    alpha2: 'MHL',
    numeric: '584',
  },
  {
    name: 'Martinique',
    alpha2: 'MQ',
    alpha2: 'MTQ',
    numeric: '474',
  },
  {
    name: 'Mauritania',
    alpha2: 'MR',
    alpha2: 'MRT',
    numeric: '478',
  },
  {
    name: 'Mauritius',
    alpha2: 'MU',
    alpha2: 'MUS',
    numeric: '480',
  },
  {
    name: 'Mayotte',
    alpha2: 'YT',
    alpha2: 'MYT',
    numeric: '175',
  },
  {
    name: 'Mexico',
    alpha2: 'MX',
    alpha2: 'MEX',
    numeric: '484',
  },
  {
    name: 'Micronesia   (Federated  States   of)',
    alpha2: 'FM',
    alpha2: 'FSM',
    numeric: '583',
  },
  {
    name: 'Moldova (the   Republic  of)',
    alpha2: 'MD',
    alpha2: 'MDA',
    numeric: '498',
  },
  {
    name: 'Monaco',
    alpha2: 'MC',
    alpha2: 'MCO',
    numeric: '492',
  },
  {
    name: 'Mongolia',
    alpha2: 'MN',
    alpha2: 'MNG',
    numeric: '496',
  },
  {
    name: 'Montenegro',
    alpha2: 'ME',
    alpha2: 'MNE',
    numeric: '499',
  },
  {
    name: 'Montserrat',
    alpha2: 'MS',
    alpha2: 'MSR',
    numeric: '500',
  },
  {
    name: 'Morocco',
    alpha2: 'MA',
    alpha2: 'MAR',
    numeric: '504',
  },
  {
    name: 'Mozambique',
    alpha2: 'MZ',
    alpha2: 'MOZ',
    numeric: '508',
  },
  {
    name: 'Myanmar',
    alpha2: 'MM',
    alpha2: 'MMR',
    numeric: '104',
  },
  {
    name: 'Namibia',
    alpha2: 'NA',
    alpha2: 'NAM',
    numeric: '516',
  },
  {
    name: 'Nauru',
    alpha2: 'NR',
    alpha2: 'NRU',
    numeric: '520',
  },
  {
    name: 'Nepal',
    alpha2: 'NP',
    alpha2: 'NPL',
    numeric: '524',
  },
  {
    name: 'Netherlands (the)',
    alpha2: 'NL',
    alpha2: 'NLD',
    numeric: '528',
  },
  {
    name: 'New Caledonia',
    alpha2: 'NC',
    alpha2: 'NCL',
    numeric: '540',
  },
  {
    name: 'New Zealand',
    alpha2: 'NZ',
    alpha2: 'NZL',
    numeric: '554',
  },
  {
    name: 'Nicaragua',
    alpha2: 'NI',
    alpha2: 'NIC',
    numeric: '558',
  },
  {
    name: 'Niger (the)',
    alpha2: 'NE',
    alpha2: 'NER',
    numeric: '562',
  },
  {
    name: 'Nigeria',
    alpha2: 'NG',
    alpha2: 'NGA',
    numeric: '566',
  },
  {
    name: 'Niue',
    alpha2: 'NU',
    alpha2: 'NIU',
    numeric: '570',
  },
  {
    name: 'Norfolk Island',
    alpha2: 'NF',
    alpha2: 'NFK',
    numeric: '574',
  },
  {
    name: 'Northern   Mariana   Islands   (the)',
    alpha2: 'MP',
    alpha2: 'MNP',
    numeric: '580',
  },
  {
    name: 'Norway',
    alpha2: 'NO',
    alpha2: 'NOR',
    numeric: '578',
  },
  {
    name: 'Oman',
    alpha2: 'OM',
    alpha2: 'OMN',
    numeric: '512',
  },
  {
    name: 'Pakistan',
    alpha2: 'PK',
    alpha2: 'PAK',
    numeric: '586',
  },
  {
    name: 'Palau',
    alpha2: 'PW',
    alpha2: 'PLW',
    numeric: '585',
  },
  {
    name: 'Palestine, State of',
    alpha2: 'PS',
    alpha2: 'PSE',
    numeric: '275',
  },
  {
    name: 'Panama',
    alpha2: 'PA',
    alpha2: 'PAN',
    numeric: '591',
  },
  {
    name: 'Papua New Guinea',
    alpha2: 'PG',
    alpha2: 'PNG',
    numeric: '598',
  },
  {
    name: 'Paraguay',
    alpha2: 'PY',
    alpha2: 'PRY',
    numeric: '600',
  },
  {
    name: 'Peru',
    alpha2: 'PE',
    alpha2: 'PER',
    numeric: '604',
  },
  {
    name: 'Philippines (the)',
    alpha2: 'PH',
    alpha2: 'PHL',
    numeric: '608',
  },
  {
    name: 'Pitcairn',
    alpha2: 'PN',
    alpha2: 'PCN',
    numeric: '612',
  },
  {
    name: 'Poland',
    alpha2: 'PL',
    alpha2: 'POL',
    numeric: '616',
  },
  {
    name: 'Portugal',
    alpha2: 'PT',
    alpha2: 'PRT',
    numeric: '620',
  },
  {
    name: 'Puerto   Rico',
    alpha2: 'PR',
    alpha2: 'PRI',
    numeric: '630',
  },
  {
    name: 'Qatar',
    alpha2: 'QA',
    alpha2: 'QAT',
    numeric: '634',
  },
  {
    name: 'Republic   of  North  Macedonia',
    alpha2: 'MK',
    alpha2: 'MKD',
    numeric: '807',
  },
  {
    name: 'Romania',
    alpha2: 'RO',
    alpha2: 'ROU',
    numeric: '642',
  },
  {
    name: 'Russian Federation   (the)',
    alpha2: 'RU',
    alpha2: 'RUS',
    numeric: '643',
  },
  {
    name: 'Rwanda',
    alpha2: 'RW',
    alpha2: 'RWA',
    numeric: '646',
  },
  {
    name: 'Réunion',
    alpha2: 'RE',
    alpha2: 'REU',
    numeric: '638',
  },
  {
    name: 'Saint Barthélemy',
    alpha2: 'BL',
    alpha2: 'BLM',
    numeric: '652',
  },
  {
    name: 'Saint Helena,   Ascension   and   Tristan   da Cunha',
    alpha2: 'SH',
    alpha2: 'SHN',
    numeric: '654',
  },
  {
    name: 'Saint Kitts and Nevis',
    alpha2: 'KN',
    alpha2: 'KNA',
    numeric: '659',
  },
  {
    name: 'Saint Lucia',
    alpha2: 'LC',
    alpha2: 'LCA',
    numeric: '662',
  },
  {
    name: 'Saint Martin   (French   part)',
    alpha2: 'MF',
    alpha2: 'MAF',
    numeric: '663',
  },
  {
    name: 'Saint Pierre   and   Miquelon',
    alpha2: 'PM',
    alpha2: 'SPM',
    numeric: '666',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    alpha2: 'VC',
    alpha2: 'VCT',
    numeric: '670',
  },
  {
    name: 'Samoa',
    alpha2: 'WS',
    alpha2: 'WSM',
    numeric: '882',
  },
  {
    name: 'San Marino',
    alpha2: 'SM',
    alpha2: 'SMR',
    numeric: '674',
  },
  {
    name: 'Sao Tome   and   Principe',
    alpha2: 'ST',
    alpha2: 'STP',
    numeric: '678',
  },
  {
    name: 'Saudi Arabia',
    alpha2: 'SA',
    alpha2: 'SAU',
    numeric: '682',
  },
  {
    name: 'Senegal',
    alpha2: 'SN',
    alpha2: 'SEN',
    numeric: '686',
  },
  {
    name: 'Serbia',
    alpha2: 'RS',
    alpha2: 'SRB',
    numeric: '688',
  },
  {
    name: 'Seychelles',
    alpha2: 'SC',
    alpha2: 'SYC',
    numeric: '690',
  },
  {
    name: 'Sierra   Leone',
    alpha2: 'SL',
    alpha2: 'SLE',
    numeric: '694',
  },
  {
    name: 'Singapore',
    alpha2: 'SG',
    alpha2: 'SGP',
    numeric: '702',
  },
  {
    name: 'Sint   Maarten   (Dutch part)',
    alpha2: 'SX',
    alpha2: 'SXM',
    numeric: '534',
  },
  {
    name: 'Slovakia',
    alpha2: 'SK',
    alpha2: 'SVK',
    numeric: '703',
  },
  {
    name: 'Slovenia',
    alpha2: 'SI',
    alpha2: 'SVN',
    numeric: '705',
  },
  {
    name: 'Solomon Islands',
    alpha2: 'SB',
    alpha2: 'SLB',
    alpha2: '090',
  },
  {
    name: 'Somalia',
    alpha2: 'SO',
    alpha2: 'SOM',
    numeric: '706',
  },
  {
    name: 'South Africa',
    alpha2: 'ZA',
    alpha2: 'ZAF',
    numeric: '710',
  },
  {
    name: 'South Georgia and the South Sandwich   Islands',
    alpha2: 'GS',
    alpha2: 'SGS',
    numeric: '239',
  },
  {
    name: 'South Sudan',
    alpha2: 'SS',
    alpha2: 'SSD',
    numeric: '728',
  },
  {
    name: 'Spain',
    alpha2: 'ES',
    alpha2: 'ESP',
    numeric: '724',
  },
  {
    name: 'Sri Lanka',
    alpha2: 'LK',
    alpha2: 'LKA',
    numeric: '144',
  },
  {
    name: 'Sudan (the)',
    alpha2: 'SD',
    alpha2: 'SDN',
    numeric: '729',
  },
  {
    name: 'Suriname',
    alpha2: 'SR',
    alpha2: 'SUR',
    numeric: '740',
  },
  {
    name: 'Svalbard   and   Jan   Mayen',
    alpha2: 'SJ',
    alpha2: 'SJM',
    numeric: '744',
  },
  {
    name: 'Sweden',
    alpha2: 'SE',
    alpha2: 'SWE',
    numeric: '752',
  },
  {
    name: 'Switzerland',
    alpha2: 'CH',
    alpha2: 'CHE',
    numeric: '756',
  },
  {
    name: 'Syrian   Arab  Republic',
    alpha2: 'SY',
    alpha2: 'SYR',
    numeric: '760',
  },
  {
    name: 'Taiwan   (Province   of China)',
    alpha2: 'TW',
    alpha2: 'TWN',
    numeric: '158',
  },
  {
    name: 'Tajikistan',
    alpha2: 'TJ',
    alpha2: 'TJK',
    numeric: '762',
  },
  {
    name: 'Tanzania,  United  Republic   of',
    alpha2: 'TZ',
    alpha2: 'TZA',
    numeric: '834',
  },
  {
    name: 'Thailand',
    alpha2: 'TH',
    alpha2: 'THA',
    numeric: '764',
  },
  {
    name: 'Timor-Leste',
    alpha2: 'TL',
    alpha2: 'TLS',
    numeric: '626',
  },
  {
    name: 'Togo',
    alpha2: 'TG',
    alpha2: 'TGO',
    numeric: '768',
  },
  {
    name: 'Tokelau',
    alpha2: 'TK',
    alpha2: 'TKL',
    numeric: '772',
  },
  {
    name: 'Tonga',
    alpha2: 'TO',
    alpha2: 'TON',
    numeric: '776',
  },
  {
    name: 'Trinidad   and   Tobago',
    alpha2: 'TT',
    alpha2: 'TTO',
    numeric: '780',
  },
  {
    name: 'Tunisia',
    alpha2: 'TN',
    alpha2: 'TUN',
    numeric: '788',
  },
  {
    name: 'Turkey',
    alpha2: 'TR',
    alpha2: 'TUR',
    numeric: '792',
  },
  {
    name: 'Turkmenistan',
    alpha2: 'TM',
    alpha2: 'TKM',
    numeric: '795',
  },
  {
    name: 'Turks and Caicos   Islands   (the)',
    alpha2: 'TC',
    alpha2: 'TCA',
    numeric: '796',
  },
  {
    name: 'Tuvalu',
    alpha2: 'TV',
    alpha2: 'TUV',
    numeric: '798',
  },
  {
    name: 'Uganda',
    alpha2: 'UG',
    alpha2: 'UGA',
    numeric: '800',
  },
  {
    name: 'Ukraine',
    alpha2: 'UA',
    alpha2: 'UKR',
    numeric: '804',
  },
  {
    name: 'United   Arab  Emirates   (the)',
    alpha2: 'AE',
    alpha2: 'ARE',
    numeric: '784',
  },
  {
    name: 'United   Kingdom   of Great Britain and Northern   Ireland   (the)',
    alpha2: 'GB',
    alpha2: 'GBR',
    numeric: '826',
  },
  {
    name: 'United   States  Minor  Outlying   Islands   (the)',
    alpha2: 'UM',
    alpha2: 'UMI',
    numeric: '581',
  },
  {
    name: 'United   States  of   America   (the)',
    alpha2: 'US',
    alpha2: 'USA',
    numeric: '840',
  },
  {
    name: 'Uruguay',
    alpha2: 'UY',
    alpha2: 'URY',
    numeric: '858',
  },
  {
    name: 'Uzbekistan',
    alpha2: 'UZ',
    alpha2: 'UZB',
    numeric: '860',
  },
  {
    name: 'Vanuatu',
    alpha2: 'VU',
    alpha2: 'VUT',
    numeric: '548',
  },
  {
    name: 'Venezuela (Bolivarian Republic   of)',
    alpha2: 'VE',
    alpha2: 'VEN',
    numeric: '862',
  },
  {
    name: 'Viet   Nam',
    alpha2: 'VN',
    alpha2: 'VNM',
    numeric: '704',
  },
  {
    name: 'Virgin   Islands   (British)',
    alpha2: 'VG',
    alpha2: 'VGB',
    alpha2: '092',
  },
  {
    name: 'Virgin   Islands   (U.S.)',
    alpha2: 'VI',
    alpha2: 'VIR',
    numeric: '850',
  },
  {
    name: 'Wallis   and   Futuna',
    alpha2: 'WF',
    alpha2: 'WLF',
    numeric: '876',
  },
  {
    name: 'Western Sahara',
    alpha2: 'EH',
    alpha2: 'ESH',
    numeric: '732',
  },
  {
    name: 'Yemen',
    alpha2: 'YE',
    alpha2: 'YEM',
    numeric: '887',
  },
  {
    name: 'Zambia',
    alpha2: 'ZM',
    alpha2: 'ZMB',
    numeric: '894',
  },
  {
    name: 'Zimbabwe',
    alpha2: 'ZW',
    alpha2: 'ZWE',
    numeric: '716',
  },
  {
    name: 'Åland Islands',
    alpha2: 'AX',
    alpha2: 'ALA',
    numeric: '248',
  },
];
